### PR TITLE
Removed import lib

### LINKED ISSUE #1: many dev dependencies are decared as dependencies + add a CONTRIBUTORS.md
These should not be dependencies:

https://github.com/monarch-initiative/monarch-project-template/blob/64889530025fa3905ee5ec814074a79b42142138/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml#L11-L19

users of the instantiated project do not these, only devs

Also sphinx should only be in one place

Also consider adding a CONTRIBUTORS.md whose audience is not *users* but *devs*. this would document SOP for adding new dev and main dependencies

See also:

- https://github.com/biolink/biolink-model-toolkit/issues/118

### PR DESCRIPTION
**Pull request by hrshdhgd**
Fixes #1

### CODE REVIEW

**Comment by cmungall** [comment]
after speaking to @pkalita-lbl I am not so sure removing this is such a good idea

**Comment by hrshdhgd** [comment]
I agree.

**Review by pkalita-lbl — CHANGES_REQUESTED** [review]
I probably wouldn't do this. The commented out code allows the package's code (and downstream clients thereof) to know it's own version number. Without it [this](https://github.com/monarch-initiative/monarch-project-template/blob/0fce395fe859618d3feb3ac9ebd2f8b94d743b2b/%7B%7Bcookiecutter.project_name%7D%7D/src/%7B%7Bcookiecutter.__project_slug%7D%7D/cli.py#L17) wouldn't work anymore.

Is `importlib-metadata` causing specific problems?

**Comment by hrshdhgd** [comment]
I didn't remove it initially but [Chris mentioned that it should be removed](https://github.com/monarch-initiative/monarch-project-template/issues/1#issuecomment-1546410067).

**Comment by pkalita-lbl** [comment]
I see. Well I'd probably leave it alone then.

**Pull request closed without merging**
